remote_theme: chrisrhymes/bulma-clean-theme

title: Allan Payeras, PhD
tagline: allanpayeras

google_analytics: G-N95N7E5JP6

permalink: pretty

fixed_navbar: top

defaults:
  -
    scope:
      path: ""
      type: "page"
    values:
      hero_image: /img/hero_default.jpg
      hero_darken: true
      hero_height: is-fullwidth