remote_theme: chrisrhymes/bulma-clean-theme

title: Allan Payeras, PhD
tagline: allanpayeras

permalink: pretty

fixed_navbar: top

defaults:
  -
    scope:
      path: ""
      type: "page"
    values:
      hero_image: /img/hero_master.jpg
      hero_darken: true