remote_theme: chrisrhymes/bulma-clean-theme

title: Allan Payeras, PhD
tagline: allanpayeras

permalink: pretty

fixed_navbar: top
defauts:
  -
    scope:
      path: ""
      type: "pages"
    values:
      hero_image: /img/hero_master.jpg
      hero_darken: true